/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const defineColadaLoader: typeof import('unplugin-vue-router/data-loaders/pinia-colada')['defineColadaLoader']
  const isLoadingData: typeof import('./composables/loading-data')['isLoadingData']
  const isNavigating: typeof import('./composables/loading-data')['isNavigating']
  const someFn: typeof import('./utils/index')['someFn']
  const useArtworkDetails: typeof import('./loaders/artwork-details')['useArtworkDetails']
  const useArtworkList: typeof import('./loaders/artwork-list')['useArtworkList']
  const useArtworkRelatedArtworks: typeof import('./loaders/artwork-details')['useArtworkRelatedArtworks']
  const useCounterStore: typeof import('./stores/counter')['useCounterStore']
}
// for vue template auto import
import { UnwrapRef } from 'vue'
declare module 'vue' {
  interface GlobalComponents {}
  interface ComponentCustomProperties {
    readonly defineColadaLoader: UnwrapRef<typeof import('unplugin-vue-router/data-loaders/pinia-colada')['defineColadaLoader']>
    readonly isNavigating: UnwrapRef<typeof import('./composables/loading-data')['isNavigating']>
    readonly someFn: UnwrapRef<typeof import('./utils/index')['someFn']>
    readonly useArtworkDetails: UnwrapRef<typeof import('./loaders/artwork-details')['useArtworkDetails']>
    readonly useArtworkList: UnwrapRef<typeof import('./loaders/artwork-list')['useArtworkList']>
    readonly useArtworkRelatedArtworks: UnwrapRef<typeof import('./loaders/artwork-details')['useArtworkRelatedArtworks']>
    readonly useCounterStore: UnwrapRef<typeof import('./stores/counter')['useCounterStore']>
  }
}
declare module '@vue/runtime-core' {
  interface GlobalComponents {}
  interface ComponentCustomProperties {
    readonly defineColadaLoader: UnwrapRef<typeof import('unplugin-vue-router/data-loaders/pinia-colada')['defineColadaLoader']>
    readonly isNavigating: UnwrapRef<typeof import('./composables/loading-data')['isNavigating']>
    readonly someFn: UnwrapRef<typeof import('./utils/index')['someFn']>
    readonly useArtworkDetails: UnwrapRef<typeof import('./loaders/artwork-details')['useArtworkDetails']>
    readonly useArtworkList: UnwrapRef<typeof import('./loaders/artwork-list')['useArtworkList']>
    readonly useArtworkRelatedArtworks: UnwrapRef<typeof import('./loaders/artwork-details')['useArtworkRelatedArtworks']>
    readonly useCounterStore: UnwrapRef<typeof import('./stores/counter')['useCounterStore']>
  }
}
